[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "channels>=4.3.2",
    "django>=6.0,<6.1",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.18,<3.19",
    "djangorestframework-simplejwt[crypto]>=5.5.1",
    "firebase-admin>=7,<8",
    "livekit-api>=1.2.1",
    "phonenumbers>=9.0.39",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.53.0",
]
