# Generated by Django 6.0.8 on 2026-10-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_devicesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicesession",
            name="installation_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
