# Generated by Django 6.0.8 on 2026-10-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_devicesession_installation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number_normalized',
            field=models.CharField(max_length=32, unique=True, verbose_name='phone number'),
        ),
    ]
