# Generated by Django 6.0.8 on 2026-10-04 00:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="installation_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                fields=("user", "installation_id"),
                name="devices_unique_user_installation_id",
            ),
        ),
    ]
