# Generated by Django 6.0.8 on 2026-10-04 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_devicesession_installation_id"),
        ("devices", "0002_device_installation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="device_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="accounts.devicesession",
            ),
        ),
    ]
