# Generated by Django 6.0.8 on 2026-09-15 09:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('livekit', 'LiveKit')], default='livekit', max_length=20)),
                ('call_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=20)),
                ('state', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('accepted', 'Accepted'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('ending', 'Ending'), ('ended', 'Ended'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('busy', 'Busy'), ('failed', 'Failed'), ('timed_out', 'Timed out')], default='initiated', max_length=20)),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('ringing_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=100)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_events', to=settings.AUTH_USER_MODEL)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calls.call')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='call',
            constraint=models.CheckConstraint(condition=models.Q(('initiator', models.F('recipient')), _negated=True), name='calls_initiator_not_recipient'),
        ),
    ]
